openapi: 3.0.0
info:
  title: Get Account Data
  version: 1.0.0
tags:
  - name: API List

parameters:
  - in: body
    name: body
    description: Transaction Data
    required: true
    schema:
      $ref: '#/definitions/Transactions'

responses:
  201:
    description: Transaction Succesfully Added
    schema:
      $ref: '#/definitions/Transactions'
  404:
    description: Account Not Found
    schema:
      $ref: '#/definitions/Transactions'
  405:
    description: Amount Below Account Balance
    schema:
      $ref: '#/definitions/Transactions'
  500:
    description: Error Occured
    schema:
      $ref: '#/definitions/Transactions'

definitions:
  Transactions:
    type: object
    properties:
      customer_name:
        type: string
        description: Customer Name
      amount:
        type: integer
        description: Transaction Amount
      date:
        type: string
        format: date
        description: Transaction Date
      type:
        type: string
        description: Transaction Type (Priority/Expense)
    required:
      - customer_name
      - amount
      - date
      - type
