openapi: 3.0.0
info:
  title: Get Account Data
  version: 1.0.0
tags:
  - name: API List

definitions:
  Transactions:
    type: object
    properties:
      transaction_id:
        type: integer
        description: Transaction ID
      account_id:
        type: integer
        description: Account ID
      amount:
        type: integer
        description: Transaction Amount
      date:
        type: date
        description: Transaction Date
      type:
        type: string
        description: Transaction Type

responses:
  200:
    description: Account List
    schema:
      type: array
      items:
        $ref: '#/definitions/Transactions'